### ISSUE TITLE
GetVolumePathNamesForVolumeName failed with Win32 error code 433

### ISSUE THREAD

**Issue by egortech** [microsoft/CopyOnWrite#44]
Looks like ``Microsoft.Build.Tasks.Copy`` failed when there are some disconnected drives with have drive letter mapping.

```
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061: The "Copy" task could not be instantiated from "E:\packages\nuget\microsoft.build.copyonwrite\1.0.315\build\netstandard2.0\Microsoft.Build.CopyOnWrite.dll". 
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception. ---> System.ComponentModel.Win32Exception: GetVolumePathNamesForVolumeName(\\?\Volume{55eecc11-0000-0000-0002-000000000000}\) failed with Win32 error code 433
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.CopyOnWrite.Windows.VolumeEnumerator.GetVolumePathNamesForVolumeName(String volumeName, Dictionary`2 driveLetterUpperToSubstDriveLettersUpper) in D:\CoW\lib\Windows\VolumeEnumerator.cs:line 128
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.CopyOnWrite.Windows.VolumeEnumerator.<GetVolumesAndVolumePaths>d__2.MoveNext() in D:\CoW\lib\Windows\VolumeEnumerator.cs:line 120
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.CopyOnWrite.Windows.VolumeInfoCache.BuildFromCurrentFilesystem() in D:\CoW\lib\Windows\VolumeInfoCache.cs:line 34
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.CopyOnWrite.CopyOnWriteFilesystemFactory.Create() in D:\CoW\lib\CopyOnWriteFilesystemFactory.cs:line 48
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at System.Lazy`1.CreateValue()
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at System.Lazy`1.LazyInitValue()
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.Build.Tasks.Copy..cctor()
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    --- End of inner exception stack trace ---
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB4061:    at Microsoft.Build.Tasks.Copy..ctor()
```

 mountvol.exe gives me this output:

```
Possible values for VolumeName along with current mount points are:

    \\?\Volume{c798f43e-be3d-46a4-a0ed-4398088b775d}\
        I:\

    \\?\Volume{42165081-1a13-4bff-b2bf-2bd6b39af7e6}\
        C:\

    \\?\Volume{530e87c3-1667-43ff-b3cb-880ba5f4ac0b}\
        *** NO MOUNT POINTS ***

    \\?\Volume{2473cbb0-dcb5-42ac-b360-72e29db43828}\
        E:\

    \\?\Volume{18c7dd90-7ca1-4c6a-b58d-7949b027cbdc}\
        D:\

    \\?\Volume{a3f3fd35-9d09-476d-9954-ef650995739a}\
        *** NO MOUNT POINTS ***

    \\?\Volume{55eecc11-0000-0000-0002-000000000000}\
A device which does not exist was specified.
    \\?\Volume{d7a4bec3-0000-0000-0002-000000000000}\
A device which does not exist was specified.
```

I believe that the task should ignore that drives. CoW target was on 2473cbb0-dcb5-42ac-b360-72e29db43828 drive

**Comment by stan-sz** [comment]
This is similar issue to #41 just the crash is on line

https://github.com/microsoft/CopyOnWrite/blob/191d3d6f3ee6c53ca16e49c3c98a897e6f2e9014/lib/Windows/VolumeInfoCache.cs#L34
